[2024-08-13T16:57:34.812+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-13T16:57:34.826+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: podcast_summary.download_episodes manual__2024-08-13T16:57:30.080420+00:00 [queued]>
[2024-08-13T16:57:34.829+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: podcast_summary.download_episodes manual__2024-08-13T16:57:30.080420+00:00 [queued]>
[2024-08-13T16:57:34.830+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-13T16:57:34.837+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): download_episodes> on 2024-08-13 16:57:30.080420+00:00
[2024-08-13T16:57:34.840+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1274) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-13T16:57:34.841+0000] {standard_task_runner.py:64} INFO - Started process 1276 to run task
[2024-08-13T16:57:34.843+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'podcast_summary', 'download_episodes', 'manual__2024-08-13T16:57:30.080420+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpn7x0p2bt']
[2024-08-13T16:57:34.844+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask download_episodes
[2024-08-13T16:57:34.869+0000] {task_command.py:426} INFO - Running <TaskInstance: podcast_summary.download_episodes manual__2024-08-13T16:57:30.080420+00:00 [running]> on host 2370a6900c77
[2024-08-13T16:57:34.928+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='podcast_summary' AIRFLOW_CTX_TASK_ID='download_episodes' AIRFLOW_CTX_EXECUTION_DATE='2024-08-13T16:57:30.080420+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-13T16:57:30.080420+00:00'
[2024-08-13T16:57:34.929+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-13T16:57:34.930+0000] {logging_mixin.py:188} INFO - Downloading the-ol-stock-bond-balancing-act.mp3
[2024-08-13T16:57:44.658+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-13T16:57:44.659+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 72, in download_episodes
    with open(audio_path, "wb+") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'episodes/the-ol-stock-bond-balancing-act.mp3'
[2024-08-13T16:57:44.673+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=podcast_summary, task_id=download_episodes, run_id=manual__2024-08-13T16:57:30.080420+00:00, execution_date=20240813T165730, start_date=20240813T165734, end_date=20240813T165744
[2024-08-13T16:57:44.685+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task download_episodes ([Errno 2] No such file or directory: 'episodes/the-ol-stock-bond-balancing-act.mp3'; 1276)
[2024-08-13T16:57:44.697+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-13T16:57:44.706+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-13T16:57:44.707+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
